### ISSUE TITLE
Add latex Bracket package to MathJax preview

### ISSUE THREAD

**Issue by brianjoubert** [Jackiexiao/foam-mkdocs-template#4]
Hello,

I am using your MKDocs template for Foam to serve it on a server. It is actually working very well so thank you very much! I added mdx_math to the extensions and 

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

to the Yaml file. The math display very well except the braket notation (for quantum physics notation), this kind:

https://tex.stackexchange.com/questions/214728/braket-notation-in-latex

Can I load additional packages to be able to display it correctly? 

Best and thanks again

**Comment by makerjackie** [comment]
glad to hear this repo help you!

I am not sure why `\braket{0|0}` not work, maybe you ask [here: mkdocs-material](https://github.com/squidfunk/mkdocs-material) for help

**Comment by brianjoubert** [comment]
Thanks,

I saw they added an extension for mathjax 3

I tried to change 

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0?/MathJax.js?config=TeX-AMS-MML_HTMLorMML

to 

https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2?/MathJax.js?config=TeX-AMS-MML_HTMLorMML


But it does not work 


Also it seems here that there is a physics package (for mathjax 2.7) I could maybe use:

https://github.com/mathjax/MathJax-third-party-extensions

Do you know how to add extensions?

Sorry I am really a beginner in all that

Thanks again

**Comment by makerjackie** [comment]
sorry, I am not familiar with the solution to the problem you are facing.  It may be helpful to consult with someone who has more expertise in this area,

**Comment by brianjoubert** [comment]
Ok thanks,

Will try to wait for an answer on the mk docs github

**Comment by brianjoubert** [comment]
Hi!

So I finally got a really answer for that. First now it is using MathJax 3 and it is also loading the physics package. Here is the answer

Note that your mkdocs.yaml file should include

```
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```



and that you need to create a file docs/javascript/mathjax.js containing
```
window.MathJax = {
  loader: {load: ['[tex]/physics']},
  tex: {
    packages: {'[+]': 'physics'},
    inlineMath: [["\\(", "\\)"]],
    displayMath: [["\\[", "\\]"]],
    processEscapes: true,
    processEnvironments: true
  },
  options: {
    ignoreHtmlClass: ".*|",
    processHtmlClass: "arithmatex"
  }
};

document$.subscribe(() => {
  MathJax.typesetPromise()
})
```
Hope it will help other people
